hostname: localhost
port: 8080
secure: false
pool_size: 2
acquire_timeout: 5

metrics:
  enabled: True
  filename: "metrics.jsonl"

webui:
  model_name: SeamlessM4T
  tgt_supported_langs:
    - eng: "ğŸ‡¬ğŸ‡§ English"
    - ita: "ğŸ‡®ğŸ‡¹ Italian"
  src_supported_langs:
    - eng: "ğŸ‡¬ğŸ‡§ English"
    - ita: "ğŸ‡®ğŸ‡¹ Italian"
